### ISSUE TITLE
libdoc2testbench incompatible with Robot Framework 5

### ISSUE THREAD

**Issue by falk7** [imbus/robotframework-libdoc2testbench#9]
converting .resource files does not work using robot framework 5.

``` bash
$ libdoc2testbench.exe test/test.resource 
resource: test
  1 Interactions
Traceback (most recent call last):
  File "C:\Users\Falk\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main        
    return _run_code(code, main_globals, None,
  File "C:\Users\Falk\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Falk\AppData\Local\Programs\Python\Python39\Scripts\libdoc2testbench.exe\__main__.py", line 7, in <60, in create_project_dump
    libraries, resources = get_libdoc_lists(lib_or_res, lib_name, lib_version,  File "C:\Users\Falk\AppData\Local\Programs\Python\Python39\lib\site-packages\Libdoc2TestBench\__init__.py", line 254, in get_libdoc_lists
    print_stat(libdoc)  File "C:\Users\Falk\AppData\Local\Programs\Python\Python39\lib\site-packages\Libdoc2TestBench\__init__.py", line 265, in print_stat
    if libdoc.data_types and libdoc.data_types.enums:AttributeError: 'LibraryDoc' object has no attribute 'data_types'
```

After downgrading to robot framework 4.1.3 it worked again

**Comment by falk7** [comment]
I thin i fixed the method:

```
def print_stat(libdoc: LibraryDoc):
    print(f"{libdoc.type.lower()}: {libdoc.name}")
    print(f"  {len(libdoc.keywords)} Interactions")
    
    data_types = libdoc.to_dictionary()["dataTypes"]
    if data_types and data_types.enums:
        print(f"  {len(data_types.enums)} Data Types")
```

I will test it and create a pull request

**Comment by HenrikSchuette** [comment]
Release 1.2.0 is compatible with Robot Framework > 5.0.0
